[package]
name = "motor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial ={path="../serial", default-features = false}

[features]
std=["serial/std"]
default =["std"]
